kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-stream-protobuf-v1
  namespace: processing
  labels:
    app: kafka-stream-protobuf
    version: v1
data:
  application.yaml: |
    server:
      port: 8080
      servlet:
        contextPath: /v1
    # set spring profile active
    spring.profiles.active: word-count
    kafka:
      application-id: kafka-stream-applicaiton
      bootstrap-servers: my-cluster-2-kafka-bootstrap.kafka2.svc.cluster.local:9092
      client.id: client-kafka-stream-applicaiton
      group.id: group-kafka-stream-applicaiton
      # movie rated example config
      state.dir: /state/data
      movie.topic.name: movies
      rekeyed.movie.topic.name: rekeyed-movies
      rating.topic.name: ratings
      rated.movies.topic.name: rated-movies
      # word count example config
      text.count.input.topic: streams-plaintext-input
      word.count.output.topic: streams-wordcount-output
      word.count.state.dir: /state/word