apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-stream-protobuf-v1
  annotations:
    deployment.kubernetes.io/revision: "SNAPSHOT"
  namespace: processing
  labels:
    app: kafka-stream-protobuf
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-stream-protobuf
      version: v1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "SNAPSHOT"
      labels:
        app: kafka-stream-protobuf
        version: v1
    spec:
      containers:
        - name: kafka-stream-protobuf
          image: com.kafka.stream:kafka-stream-1.0.0-SNAPSHOT
          env:
            - name: CONFIG_LOC
              value: file:/config/
            - name: JAVA_OPTS
              value: -XX:MaxMetaspaceSize=128M -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555 -Dcom.sun.management.jmxremote.rmi.port=5555 -Djava.rmi.server.hostname=127.0.0.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 1024Mi
              cpu: 300m
            limits:
              memory: 1024Mi
              cpu: 300m
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /state
              name: state-volume
            - mountPath: /metrics
              name: metrics-volume
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: state-volume
          emptyDir: { }
        - name: metrics-volume
          configMap:
            name: kafka-stream-protobuf-v1
            items:
              - key: metrics.yaml
                path: metrics.yaml
                mode:
        - name: config-volume
          configMap:
            name: kafka-stream-protobuf-v1
            items:
              - key: application.yaml
                path: application.yaml
                mode: 0755