apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: processing
type: Opaque
data:
  application.yaml: YXp1cmU6CiAgYXBwbGljYXRpb24taW5zaWdodHM6CiAgICBpbnN0cnVtZW50YXRpb24ta2V5OiBkOTg0NzdiMS1iMTY3LTQ2MzEtYTEzYi02NmMwODA4NzE2ZWMKICBjb25uZWN0aW9uLXN0cmluZzogRGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWVjb2VuZXJneWNvbmZpZ3JlcG87QWNjb3VudEtleT1ZTmR5OURoR0tqdS9KUUc1Ny9XQXlwS05WaVZCazltWFNYc1dwblF0aGVpSEQvbXlERzhYdkNxdlF5K1EzN3ZVaVpQMkcvdU9IVlMrTVo3YmptRmJEUT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQK