apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-stream-protobuf-pod-monitor
  labels:
    app: kafka-stream-protobuf
    version: v1
spec:
  selector:
    matchLabels:
      app: kafka-stream-protobuf
      version: v1
  podMetricsEndpoints:
    - port: ui-port
  namespaceSelector:
    matchNames: ["processing"]